[tool.poetry]
name = "betterspread"
version = "0.1.5"
description = ""
authors = ["Md Shahriyar Alam <contact@shahriyar.dev>"]
readme = "README.md"
license = "MIT"

[tool.poetry.urls]
homepage = "https://github.com/shahriyardx/betterspread"
repository = "https://github.com/shahriyardx/betterspread"
"Bug Tracker" = "https://github.com/shahriyardx/betterspread/issues"

[tool.poetry.dependencies]
python = "^3.9"
gspread = "^5.12.0"
jupyter = "^1.0.0"
gspread-formatting = "^1.1.2"


[tool.poetry.group.dev.dependencies]
black = "^23.11.0"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

